[build]
  # Directory to change to before starting a build. 
  # This is where we will look for package.json/.nvmrc/etc.
  base = "crossroads.net/"

[build.environment]
  IN_MAESTRO = '0'
  CRDS_ENV = 'int'
  CRDS_COOKIE_DOMAIN = '.crossroads.net'
  CROSSROADS_API_TOKEN = 'fa7f9234-14c3-4a04-86ce-58b1de416e8e'
  CRDS_APP_SERVER_ENDPOINT = 'https://int.crossroads.net/'
  CRDS_GATEWAY_CLIENT_ENDPOINT = 'https://gatewayint.crossroads.net/gateway/'
  CRDS_CMS_CLIENT_ENDPOINT = 'https://contentint.crossroads.net/'
  CRDS_SERVICES_CLIENT_ENDPOINT = 'https://gatewayint.crossroads.net'
  CRDS_GOOGLE_API_KEY = 'AIzaSyArKsBK97N0Wi-69x10OL7Sx57Fwlmu6Cs'
  CRDS_STRIPE_PUBKEY = 'pk_test_U8U15gSZFM4AQtPDLHYnKWqH'
  CRDS_AWS_SEARCH_ENDPOINT = 'https://aiegj2xpqh.execute-api.us-east-1.amazonaws.com/Int/'
  CRDS_STREAMSPOT_ENDPOINT = 'https://api.streamspot.com/'
  CRDS_STREAMSPOT_API_KEY = 'a0cb38cb-8146-47c2-b11f-6d93f4647389'
  CRDS_STREAMSPOT_SSID = 'crossr30e3'
  CRDS_STREAMSPOT_PLAYER_ID = '2887fba1'
  HEADER_CONTENTBLOCK_TITLE = 'sharedGlobalHeader'
  CRDS_APP_CLIENT_ENDPOINT = '/'
  DEPLOY_URL = $DEPLOY_URL

[context.production.environment]
  IN_MAESTRO = '0'
  CRDS_ENV = ''
  CRDS_COOKIE_DOMAIN = '.crossroads.net'
  CROSSROADS_API_TOKEN = 'd3f9a2f7-7dad-44ba-bfb5-58185af9f840'
  CRDS_APP_SERVER_ENDPOINT = 'https://www.crossroads.net/'
  CRDS_GATEWAY_CLIENT_ENDPOINT = 'https://gateway.crossroads.net/gateway/'
  CRDS_CMS_CLIENT_ENDPOINT = 'https://content.crossroads.net/'
  CRDS_SERVICES_CLIENT_ENDPOINT = 'https://gateway.crossroads.net/'
  CRDS_GOOGLE_API_KEY = 'AIzaSyAlv_y_ltF9naBkMhQOpg_aFas6AD6Hpzg'
  CRDS_STRIPE_PUBKEY = 'pk_live_gOVUlu5BkiMc0XXJTUosgflG'
  CRDS_AWS_SEARCH_ENDPOINT = 'https://vs9gac5tz7.execute-api.us-east-1.amazonaws.com/prod/'
  CRDS_STREAMSPOT_ENDPOINT = 'https://api.streamspot.com/'
  CRDS_STREAMSPOT_API_KEY = '82437b4d-4e38-42e2-83b6-148fcfaf36fb'
  CRDS_STREAMSPOT_SSID = 'crossr4915'
  CRDS_STREAMSPOT_PLAYER_ID = '1adb55de'
  HEADER_CONTENTBLOCK_TITLE = 'sharedGlobalHeader'
  CRDS_APP_CLIENT_ENDPOINT = '/'
  DEPLOY_URL = $DEPLOY_URL

[context.branch-deploy.environment]

[context.deploy-preview.environment]

[context.development.environment]

[context.master.environment]

[context.release.environment]
  IN_MAESTRO = '0'
  CRDS_ENV = 'demo'
  CRDS_COOKIE_DOMAIN = '.crossroads.net'
  CROSSROADS_API_TOKEN = '9a3f6689-679e-425a-a3b5-ee7b73665ebb'
  CRDS_APP_SERVER_ENDPOINT = 'https://demo.crossroads.net/'
  CRDS_GATEWAY_CLIENT_ENDPOINT = 'https://gatewaydemo.crossroads.net/gateway/'
  CRDS_CMS_CLIENT_ENDPOINT = 'https://contentdemo.crossroads.net/'
  CRDS_SERVICES_CLIENT_ENDPOINT = 'https://gatewaydemo.crossroads.net/'
  CRDS_GOOGLE_API_KEY = 'AIzaSyArKsBK97N0Wi-69x10OL7Sx57Fwlmu6Cs'
  CRDS_STRIPE_PUBKEY = 'pk_test_TR1GulD113hGh2RgoLhFqO0M'
  CRDS_AWS_SEARCH_ENDPOINT = 'https://vcag8upmga.execute-api.us-east-1.amazonaws.com/Demo/'
  CRDS_STREAMSPOT_ENDPOINT = 'https://api.streamspot.com/'
  CRDS_STREAMSPOT_API_KEY = 'a0cb38cb-8146-47c2-b11f-6d93f4647389'
  CRDS_STREAMSPOT_SSID = 'crossr30e3'
  CRDS_STREAMSPOT_PLAYER_ID = '2887fba1'
  HEADER_CONTENTBLOCK_TITLE = 'sharedGlobalHeader'
  CRDS_APP_CLIENT_ENDPOINT = '/'
  DEPLOY_URL = $DEPLOY_URL



